package com.login;

import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

public class AddFav extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        PrintWriter out = response.getWriter();
        response.setContentType("text/html");
        out.print("section {\n"
                + "            padding: 60px 0;\n"
                + "            min-height: 100vh;\n"
                + "        }\n"
                + ".section_title {\n"
                + "  margin-bottom: 40px;\n"
                + "}\n"
                + "\n"
                + ".section_title h2 {\n"
                + "  color: #333333;\n"
                + "  font-size: 25px;\n"
                + "  font-weight: 700;\n"
                + "  letter-spacing: 1.8px;\n"
                + "  text-transform: uppercase;\n"
                + "}\n"
                + "\n"
                + ".brand_border .fa.fa-minus {\n"
                + "    color: #fff;\n"
                + "    font-size: 8px;\n"
                + "    height: 2px;\n"
                + "        background: #F8C01B none repeat scroll 0 0;\n"
                + "    width: 100px;\n"
                + "}\n"
                + ".brand_border .fas.fa-handshake {\n"
                + "    font-size: 14px;\n"
                + "        color:#000000;\n"
                + "}\n"
                + "\n"
                + "\n"
                + ".section_title p {\n"
                + "  color: #333333;\n"
                + "  font-size: 14px;\n"
                + "  line-height: 25px;\n"
                + "  padding: 14px 0;\n"
                + "}\n"
                + "\n"
                + "\n"
                + ".tables-page-section .table {\n"
                + "  text-align: center;\n"
                + "  margin-bottom: 40px;\n"
                + "}\n"
                + ".tables-page-section .table th {\n"
                + "  border-bottom: 1px solid #ffffff;\n"
                + "  border-right: 1px solid #ffffff;\n"
                + "  font-family: 'Montserrat', sans-serif;\n"
                + "  font-size: 15px;\n"
                + "  font-weight: 700;\n"
                + "  padding: 10px 20px;\n"
                + "  text-align: center;\n"
                + "}\n"
                + ".tables-page-section .table td {\n"
                + "  border-bottom: 1px solid #ffffff;\n"
                + "  border-right: 1px solid #ffffff;\n"
                + "  background: #f1f1f1;\n"
                + "  font-family: 'Lato', sans-serif;\n"
                + "  font-size: 13px;\n"
                + "  color: #666666;\n"
                + "  padding: 10px 20px;\n"
                + "}\n"
                + ".tables-page-section .table thead th {\n"
                + "  padding: 15px 20px;\n"
                + "  text-align: center;\n"
                + "  background: #ffba00 !important;\n"
                + "}\n"
                + ".tables-page-section .table tr th {\n"
                + "  background: #f1f1f1;\n"
                + "}");

        out.print("<section class=\"tables-page-section\" =\"service\">\n"
                + "    <div class=\"container\">\n"
                + "     <div class=\"row\">\n"
                + "      <div class=\"col-md-12\">\n"
                + "       <div class=\"section_title text-center\">\n"
                + "         <h2>Full table responsive</h2>\n"
                + "          <div class=\"brand_border\">\n"
                + "           <i class=\"fa fa-minus\" aria-hidden=\"true\"></i> \n"
                + "           <i class=\"fas fa-handshake\"></i>\n"
                + "           <i class=\"fa fa-minus\" aria-hidden=\"true\"></i>\n"
                + "          </div>\n"
                + "         <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. <br>Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes</p>\n"
                + "       </div>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "   <div class=\"row\">\n"
                + "    <div class=\"col-sm-12\">\n"
                + "      <div class=\"table-responsive\">\n"
                + "          <table class=\"table\">\n"
                + "            <thead>\n"
                + "              <th>#</th>\n"
                + "              <th>Table Heading</th>\n"
                + "              <th>Table Heading</th>\n"
                + "              <th>Table Heading</th>\n"
                + "              <th>Table Heading</th>\n"
                + "              <th>Table Heading</th>\n"
                + "            </thead>\n"
                + "            <tr>\n"
                + "              <th>1</th>\n"
                + "              <td>Table Cell</td>\n"
                + "              <td>Table Cell</td>\n"
                + "              <td>Table Cell</td>\n"
                + "              <td>Table Cell</td>\n"
                + "              <td>Table Cell</td>\n"
                + "            </tr>\n"
                + "            <tr>\n"
                + "              <th>2</th>\n"
                + "              <td>Table Cell</td>\n"
                + "              <td>Table Cell</td>\n"
                + "              <td>Table Cell</td>\n"
                + "              <td>Table Cell</td>\n"
                + "              <td>Table Cell</td>\n"
                + "            </tr>\n"
                + "            <tr>\n"
                + "              <th>3</th>\n"
                + "              <td>Table Cell</td>\n"
                + "              <td>Table Cell</td>\n"
                + "              <td>Table Cell</td>\n"
                + "              <td>Table Cell</td>\n"
                + "              <td>Table Cell</td>\n"
                + "            </tr>\n"
                + "            <tr>\n"
                + "              <th>4</th>\n"
                + "              <td>Table Cell</td>\n"
                + "              <td>Table Cell</td>\n"
                + "              <td>Table Cell</td>\n"
                + "              <td>Table Cell</td>\n"
                + "              <td>Table Cell</td>\n"
                + "            </tr>\n"
                + "            <tr>\n"
                + "              <th>5</th>\n"
                + "              <td>Table Cell</td>\n"
                + "              <td>Table Cell</td>\n"
                + "              <td>Table Cell</td>\n"
                + "              <td>Table Cell</td>\n"
                + "              <td>Table Cell</td>\n"
                + "            </tr>\n"
                + "          </table>\n"
                + "        </div>\n"
                + "\n"
                + "    </div>\n"
                + "   </div>\n"
                + "  </div>\n"
                + " </section>");

    }

}
